### ISSUE TITLE
2 test files Exeter created for International Journal of Microsimulation

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/de-elife-continuum#1]
2 test files Exeter created for International Journal of Microsimulation
Article ID - Lax stores as a number. Test files did not work
Bot and other code it assumes the the id is numeric
Sian: Digirati have been spinning up instances and pushing content through there too

Continuum - extracted the article ID and assigned it version 1.
If not exist in Lax, give it version 1.
Should start next activity, but failed on the next one - Expand article

We think it is related to the file name pattern.
Probably a small fix - continuum test, hacks the code and revert it back. Use to work out where it next gets to.

**Comment by gnott** [comment]
I've taken a quick look and a test on the sample you provided. Here's a summary

1. First error you encountered, it was in ExpandArticle activity, and it originates from the article structure naming pattern. The matching pattern expects the article_id portion of the filename to be all digits - [0-9]. Here's an example of the bot log error

```
2017-12-12T11:51:44Z INFO worker_25242 Expanding file elife-elifetest1-vor-r1.zip
2017-12-12T11:51:44Z ERROR worker_25242 Name 'elife-elifetest1-vor-r1.zip' did not match expected pattern for status
```

2. I changed the ``[0-9]`` in the pattern to be ``[a-zA-Z0-9]`` to allow all letters and digits. I re-fed the file and it made it to the ``SendDashboardProperties`` activity. There it encountered an error with the pub date

```
2017-12-12T22:03:34Z ERROR worker_9882 Exception emitting dashboard properties
Traceback (most recent call last):
  File "/opt/elife-bot/activity/activity_SendDashboardProperties.py", line 66, in do_activity
    self.set_dashboard_properties(soup, article_id, version)
  File "/opt/elife-bot/activity/activity_SendDashboardProperties.py", line 97, in set_dashboard_properties
    pub_date = time.strftime(utils.PUB_DATE_FORMAT, parser.pub_date(soup))
TypeError: argument must be 9-item sequence, not None
```

And on the dashboard it says

```
Error in send of article properties to dashboard for article elifetest1 message:argument must be 9-item sequence, not None
```

I looked at "elife-elifetest1.xml" file in the "elife-elifetest1-vor-r1.zip" file you provided, and the pub-date has only a year

```
<pub-date date-type="publication" publication-format="electronic">
<year>2017</year>
</pub-date>
```

If the XML in the zip package had a year, month, and day then it is possible this example could make it further through the workflow (perhaps failing on a later activity, but further).

**Comment by Melissa37** [comment]
Thank you!

It had got past that and now fails at:
Copy Glencoe Still Images:
An error occurred when checking/copying Glencoe still images. Article elifetest1; message: invalid literal for int() with base 10: 'elifetest1'

**Comment by gnott** [comment]
``CopyGlencoeStillImages`` activity using the ``glencoe_check.py`` provider also expects to have a numeric article_id value. I bypassed it with a one line fix for testing purposes.

Then changed one line in ``lax_response_adapter.py`` which also expects a numeric article_id.

The sample got as far as Verify Lax Response, Lax being unable to generate JSON for it, which also looks to be related to a non-numeric article_id.

**Comment by Melissa37** [comment]
Hi there Graham

This has been sent over to Digirati to do.
It's not with us now, so closing this ticket.

@sianroderick
